# Generated by Django 5.2.3 on 2026-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('category', models.CharField(choices=[('cards', 'Карточні'), ('oral', 'Усні'), ('media', 'Медіа'), ('presentations', 'Презентації')], max_length=20, verbose_name='Категорія')),
                ('description', models.TextField(verbose_name='Опис')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Посилання на Телеграм')),
                ('rules', models.TextField(verbose_name='Правила гри')),
                ('age', models.CharField(max_length=50, verbose_name='Вік')),
                ('players_count', models.CharField(max_length=50, verbose_name='Кількість людей')),
                ('game_type', models.CharField(choices=[('educational', 'Повчальний'), ('entertaining', 'Розважальний')], max_length=20, verbose_name='Тип гри')),
                ('team_or_individual', models.CharField(choices=[('team', 'Командна'), ('individual', 'Сам за себе')], max_length=20, verbose_name='Командна / Сам за себе')),
                ('skill_developed', models.CharField(max_length=200, verbose_name='Навичка, яка розвивається')),
                ('prep_level', models.CharField(choices=[('none', 'Відкрив і почав'), ('minimal', 'Мінімальна (завантажити і відкрити)'), ('medium', 'Середня (роздрукувати, підготувати щось)')], max_length=20, verbose_name='Рівень підготовки')),
            ],
            options={
                'verbose_name': 'Гра',
                'verbose_name_plural': 'Ігри',
            },
        ),
    ]
