# Generated by Django 5.2.3 on 2026-04-24 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug (для посилання)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='GameFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Формат гри (Командна / Сам за себе)',
                'verbose_name_plural': 'Формати ігор',
            },
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Тип гри',
                'verbose_name_plural': 'Типи ігор',
            },
        ),
        migrations.CreateModel(
            name='PrepLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Рівень підготовки',
                'verbose_name_plural': 'Рівні підготовки',
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_or_individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gameformat', verbose_name='Командна / Сам за себе'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gametype', verbose_name='Тип гри'),
        ),
        migrations.AlterField(
            model_name='game',
            name='prep_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.preplevel', verbose_name='Рівень підготовки'),
        ),
    ]
