# Generated by Django 5.2.3 on 2026-04-24 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_category_gameformat_gametype_preplevel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Рівень енергії',
                'verbose_name_plural': 'Рівні енергії',
            },
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Час гри',
                'verbose_name_plural': 'Варіанти часу',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Умови (локація)',
                'verbose_name_plural': 'Умови (локації)',
            },
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Ситуація',
                'verbose_name_plural': 'Ситуації',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='energy_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.energylevel', verbose_name='Рівень енергії'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gametime', verbose_name='Час'),
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location', verbose_name='Умови (локація)'),
        ),
        migrations.AddField(
            model_name='game',
            name='situation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.situation', verbose_name='Ситуація'),
        ),
    ]
