# Generated by Django 5.2.3 on 2026-04-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_energylevel_gametime_location_situation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Фільтр: Тип взаємодії',
                'verbose_name_plural': 'Фільтри: Типи взаємодії',
            },
        ),
        migrations.CreateModel(
            name='PlayerCountRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Фільтр: Кількість гравців',
                'verbose_name_plural': 'Фільтри: Кількість гравців',
            },
        ),
        migrations.RenameModel(
            old_name='GameType',
            new_name='ActivityLevel',
        ),
        migrations.RenameModel(
            old_name='GameTime',
            new_name='AgeGroup',
        ),
        migrations.RenameModel(
            old_name='Situation',
            new_name='ContentType',
        ),
        migrations.RenameModel(
            old_name='EnergyLevel',
            new_name='GameDuration',
        ),
        migrations.RenameModel(
            old_name='GameFormat',
            new_name='GameGoal',
        ),
        migrations.AlterModelOptions(
            name='activitylevel',
            options={'verbose_name': 'Фільтр: Рівень активності', 'verbose_name_plural': 'Фільтри: Рівні активності'},
        ),
        migrations.AlterModelOptions(
            name='agegroup',
            options={'verbose_name': 'Фільтр: Вік', 'verbose_name_plural': 'Фільтри: Вік'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Фільтр: Категорія', 'verbose_name_plural': 'Фільтри: Категорії'},
        ),
        migrations.AlterModelOptions(
            name='contenttype',
            options={'verbose_name': 'Фільтр: Тип контенту', 'verbose_name_plural': 'Фільтри: Типи контенту'},
        ),
        migrations.AlterModelOptions(
            name='gameduration',
            options={'verbose_name': 'Фільтр: Тривалість', 'verbose_name_plural': 'Фільтри: Тривалість'},
        ),
        migrations.AlterModelOptions(
            name='gamegoal',
            options={'verbose_name': 'Фільтр: Ціль гри', 'verbose_name_plural': 'Фільтри: Цілі гри'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Фільтр: Місце проведення', 'verbose_name_plural': 'Фільтри: Місця проведення'},
        ),
        migrations.AlterModelOptions(
            name='preplevel',
            options={'verbose_name': 'Фільтр: Рівень підготовки', 'verbose_name_plural': 'Фільтри: Рівні підготовки'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='age',
        ),
        migrations.RemoveField(
            model_name='game',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='players_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team_or_individual',
        ),
        migrations.AddField(
            model_name='game',
            name='activity_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.activitylevel', verbose_name='Рівень активності'),
        ),
        migrations.AddField(
            model_name='game',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.agegroup', verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='game',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.contenttype', verbose_name='Тип контенту'),
        ),
        migrations.AddField(
            model_name='game',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gameduration', verbose_name='Тривалість'),
        ),
        migrations.AddField(
            model_name='game',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamegoal', verbose_name='Ціль гри'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.location', verbose_name='Місце проведення'),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_developed',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Навичка, яка розвивається'),
        ),
        migrations.AddField(
            model_name='game',
            name='interaction_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.interactiontype', verbose_name='Тип взаємодії'),
        ),
        migrations.AddField(
            model_name='game',
            name='players_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.playercountrange', verbose_name='Кількість гравців'),
        ),
    ]
