# Generated by Django 5.2.3 on 2026-04-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_interactiontype_playercountrange_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_contact_text', models.CharField(default="Зв'язатися з нами", max_length=100, verbose_name='Текст кнопки у футері')),
                ('footer_contact_link', models.URLField(blank=True, null=True, verbose_name='Посилання на Telegram у футері')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='external_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на зовнішню гру'),
        ),
        migrations.AddField(
            model_name='game',
            name='external_text',
            field=models.CharField(blank=True, default='Грати онлайн', max_length=100, null=True, verbose_name='Текст кнопки зовнішньої гри'),
        ),
        migrations.AddField(
            model_name='game',
            name='show_external',
            field=models.BooleanField(default=False, verbose_name='Показувати кнопку зовнішньої гри'),
        ),
        migrations.AddField(
            model_name='game',
            name='show_tg',
            field=models.BooleanField(default=True, verbose_name='Показувати кнопку Телеграм'),
        ),
        migrations.AddField(
            model_name='game',
            name='tg_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Телеграм'),
        ),
        migrations.AddField(
            model_name='game',
            name='tg_text',
            field=models.CharField(blank=True, default='Перейти в чат гри', max_length=100, null=True, verbose_name='Текст кнопки Телеграм'),
        ),
    ]
