# Generated by Django 5.2.3 on 2026-05-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_sitesettings_game_external_link_game_external_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thematic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Фільтр: Тематика',
                'verbose_name_plural': 'Фільтри: Тематика',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='insta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на Instagram'),
        ),
        migrations.AddField(
            model_name='game',
            name='insta_text',
            field=models.CharField(blank=True, default='Instagram', max_length=100, null=True, verbose_name='Текст кнопки Instagram'),
        ),
        migrations.AddField(
            model_name='game',
            name='show_insta',
            field=models.BooleanField(default=False, verbose_name='Показувати кнопку Instagram'),
        ),
        migrations.AddField(
            model_name='game',
            name='show_youtube',
            field=models.BooleanField(default=False, verbose_name='Показувати кнопку YouTube'),
        ),
        migrations.AddField(
            model_name='game',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на YouTube'),
        ),
        migrations.AddField(
            model_name='game',
            name='youtube_text',
            field=models.CharField(blank=True, default='YouTube', max_length=100, null=True, verbose_name='Текст кнопки YouTube'),
        ),
        migrations.AddField(
            model_name='game',
            name='thematic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.thematic', verbose_name='Тематика'),
        ),
    ]
